on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      
      - run: mkdir -p ./public/model/ && cd ./public/model/ && wget -c https://tfhub.dev/tensorflow/tfjs-model/mobilebert/1?tfjs-format=compressed -O - | tar -xz 
      - run: npm install
      - run: npm run build
      - run: zip -r release.zip build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: ./release.zip
         asset_name: release.zip
         tag: ${{ github.ref }}
         overwrite: true
         body: "This is my release text"
 